[[constraint]]
  branch = "master"
  name = "github.com/mindprince/gonvml"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.23.2"

[prune]
  go-tests = true
  unused-packages = true
