name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ealgra/nvidia_gpu_prometheus_exporter
    - name: Publish Docker image as latest
      run: docker push ealgra/nvidia_gpu_prometheus_exporter
      
